### ISSUE TITLE
Issues when put in plugins block

### ISSUE THREAD

**Issue by jriwanek** [jaredsburrows/gradle-checker-framework-plugin#10]
```
* What went wrong:
An exception occurred applying plugin request [id: 'com.jaredsburrows.checkerframework', version: '0.2.1']
> Failed to apply plugin [id 'com.jaredsburrows.checkerframework']
   > Checker plugin can only be applied to android or java projects.
```
This happens with both
```
apply plugin: 'java'
```

and 
```
plugins {
id 'java'
}

**Comment by jaredsburrows** [comment]
What version of Java are you using? It only works with Java 7/8 and/or Android projects.
```
    def jdkVersion
    if (JavaVersion.current().java7) {
      jdkVersion = ANNOTATED_JDK_NAME_JDK7
    } else if (JavaVersion.current().java8) {
      jdkVersion = ANNOTATED_JDK_NAME_JDK8
    } else {
      throw new IllegalStateException("Checker plugin only supports Java 7 and Java 8 projects.")
    }
```

**Comment by jriwanek** [comment]
I was using Java 8 u 171 at the time it occurred, all my projects require Java 8 too.

**Comment by mwhipple** [comment]
I'm also experiencing the issue...a new version just needs to be released please (preferably also including #12 😉) .

The last released version of this is very old and predates
https://github.com/jaredsburrows/gradle-checker-framework-plugin/commit/a7cc979ae612b193276c0515a9a27d29f9723184. Using a locally published copy of newer code with an appropriate `pluginManagement` configuration shows that this specific error no longer applies.

**Comment by mwhipple** [comment]
The update code no longer breaks but also doesn't apply the plugin, working on a fix.

**Comment by mwhipple** [comment]
Ignore the previous comment, I was glossing over some of the later code around integration differences and including the existing listener. The updated PR moves the rest of the logic to that hook which avoids this issue without introducing notable overhead.
