### ISSUE TITLE
Don't use evaluationDependsOnChildren

### ISSUE THREAD

**Issue by oehme** [jaredsburrows/gradle-checker-framework-plugin#7]
I can't see why this plugin would need it and it will be highly confusing to users that the plugin reverses the normal evaluation order.

**Comment by jaredsburrows** [comment]
@oehme Thanks. I wonder if that explains https://github.com/jaredsburrows/gradle-license-plugin/issues/25 because of `evaluationDependsOnChildren` here: https://github.com/jaredsburrows/gradle-license-plugin/blob/master/src/main/groovy/com/jaredsburrows/license/LicensePlugin.groovy#L11.

**Comment by oehme** [comment]
Not sure, but the checks for other plugins shouldn't be done imperatively, but with a callback. I.e. don't do this:

```
if (project.plugins.hasPlugin('somePlugin') {
}
```

instead use

```
project.plugins.withId('somePlugin') {
}
```

That way you no longer depend on the order the plugins are applied.

**Comment by jaredsburrows** [comment]
Thank you. I use `hasPlugin` in order to determine whether or not to through an exception.

**Comment by oehme** [comment]
Why throw an exception? Just do nothing :)

A plugin really shouldn't depend on order. It should either apply the other plugins it needs or it should react to others via a callback.

**Comment by jaredsburrows** [comment]
That is the thing. This plugin in particular is for java or android projects only. Android has 3 main plugins: "com.android.applicaiton", "com.android.library" and "com.android.test". I believe there are others as well for instant apps and the architecture components. When my plugins access the Android Gradle Plugin's DSL via `android { }`, it will throw an different exception. Or are you saying, simply do not "configure" the plugin if it is not compatible?

**Comment by oehme** [comment]
Exactly, only react to the plugins you care about and be a noop otherwise. Or if there is a plugin you are definitely incompatible with (and want people to know explicitly) you can react to it and throw an exception in the callback.

**Comment by jaredsburrows** [comment]
Isn't that what I am doing now? If it is not java or android project, it
will break their build, so I simply through an exception now.

Jared Burrows

*jaredsburrows@gmail.com <jaredsburrows@gmail.com>*
LinkedIn: https://www.linkedin.com/in/jaredsburrows

**Comment by oehme** [comment]
Right now your plugin only works if applied after the others. Plugins should not depend on order.

**Comment by jaredsburrows** [comment]
Ok. I removed `evaluationDependsOnChildren`. I will look into throwing an exception later down the line.

**Comment by jaredsburrows** [comment]
@oehme Where would you suggest a throw an exception in this checker framework plugin?

**Comment by jaredsburrows** [comment]
I am guessing for this plugin, it will just fail if Java plugin is not applied. For Android projects, it will just not work and the AGP plugin will throw an exception if it not setup properly. I may just be able to remove the checks entirely from this plugin.

**Comment by oehme** [comment]
I'm not sure what you mean. If you just do 

```
plugins.withId('java') {
  //do Java specific config
}
plugins.withId('android-application') {
  //do Android specific config
}
plugins.withId('android-library') {
  //do Android specific config
}
```

Everything will work as expected.

**Comment by jaredsburrows** [comment]
@oehme What is both `android-application` and `android-library` configurations are the same? See : https://github.com/jaredsburrows/gradle-license-plugin/blob/master/src/main/groovy/com/jaredsburrows/license/LicensePlugin.groovy#L12.

Since `withId` returns `void`, I would have to do the following:
```
plugins.withId('java') {
 configureJava(project)
}
plugins.withId('android-application') {
 configureAndroid(project)
}
plugins.withId('android-library') {
 configureAndroid(project)
}
```

**Comment by oehme** [comment]
Yeah or have the closure be a variable and pass it to both.

But I don't see anything Android specific in this plugin. The only line wrapped in `if (android)` is correct for the Java plugin too. In fact the code could be applied regardless of any plugin and would be correct since you are only reconfiguring Java compile tasks to have a bigger bootclasspath and processor path.

**Comment by jaredsburrows** [comment]
@oehme Something like?

```
  private def configureAndroid(def project) {
    configureAndroidProject(project)
  }

  @Override void apply(Project project) {
    project.plugins.withId("com.android.application", configureAndroid(project))

    project.plugins.withId("java") {
      configureJavaProject(project)
    }
  }
```

**Comment by jaredsburrows** [comment]
@oehme I was able to find a better way. The file `com.android.base.properties` in `com.android.build.tools:gradle-core` which is apart of `com.android.build.tools:gradle`.

```
package com.android.build.gradle.api;

import org.gradle.api.Plugin;
import org.gradle.api.Project;

/**
 * Common plugin applied by all plugins.
 *
 * <p>The purpose of this no-op plugin is to allow other plugin authors to determine if an Android
 * plugin was applied.
 */
public class AndroidBasePlugin implements Plugin<Project> {

    @Override
    public void apply(Project project) {}
}
```

I can now simplify this to:
```
  @Override void apply(Project project) {
    project.plugins.withId("com.android.base") { configureAndroidProject(project) }
    project.plugins.withId("java") { configureJavaProject(project) }
  }
```

**Comment by oehme** [comment]
Even better! :)

**Comment by C-Otto** [comment]
Sorry to hijack this, I think this was a very fruitful discussion. Is there a way to negate the `withId` check, i.e. run code only if a subproject does NOT have a specific plugin? Currently I need to use `evaluationDependsOnChildren()` in the root project because of this.

```
project.plugins.withoutId("java-test-fixtures") { // note: withOUT
    // do something after the subprojects build.gradle has been evaluated
}
```
