### ISSUE TITLE
Use sourceCompatibility, don't overwrite it

### ISSUE THREAD

**Issue by oehme** [jaredsburrows/gradle-checker-framework-plugin#8]
The plugin currently [overwrites](https://github.com/jaredsburrows/gradle-checker-framework-plugin/blob/master/src/main/groovy/com/jaredsburrows/checkerframework/CheckerPlugin.groovy#L81) the sourceCompatibility based on the Java version that the daemon is running on. This prevents cross-compilation for other versions. Instead it should use the sourceCompatibility provided by the user to decide which checker JDK to use and not mutate it.

**Comment by jaredsburrows** [comment]
@oehme Thanks for posting this.
I will use @grv87's commit to patch this here: https://github.com/jaredsburrows/gradle-checker-framework-plugin/pull/11.
